# Generated by Django 4.1.4 on 2022-12-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
